# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 299f581badbd0e4e8bc23f471170362bd5d3aa2926429582da3cf104e40bacf94976cf8596c1c3de89be3155a0c73a6b751b10ab0eed4ea00752305fd9550ce4

test:
  secret_key_base: dc614c31b1d2caa7eb336d7a69b2063e80fab1aae231a78761ed815e123f5102521093b88f639239b274378fb7932f99b7d816b453c488a41813be5862d260c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
